name: CI

on:
    push:
        branches: [main,preact]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            # 添加环境变量检查
            - name: Check env
              run: |
                echo "Checking environment variables...${{ vars.PUBLIC_UMAMI }}"
                # 列出所有环境变量（注意不要打印敏感信息）
                env | grep -v -i "secret" | grep -v -i "token"
            
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: Install pnpm
              run: npm install -g pnpm@9.14.4

            - name: Install pnpm dependencies
              run: |
                # 只安装生产依赖
                pnpm --version
                pnpm install --frozen-lockfile --prefer-offline

            - name: Run build task
              run: pnpm run build
              env:
                VITE_UMAMI: ${{ vars.VITE_UMAMI }}
                VITE_CLARITY: ${{ vars.VITE_CLARITY }}
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
                  ARGS: '-rlgoDzvc -i --delete'
                  SOURCE: 'dist/'
                  SCRIPT_BEFORE: |
                      whoami
                      ls -al
                      pwd
                  REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
                  REMOTE_USER: 'root'
                  TARGET: '/opt/1panel/apps/openresty/openresty/www/sites/resume.mengpeng.tech/index/'
                  EXCLUDE: '/node_modules/'
